In [25]:
import pandas as pd

In [26]:
df = pd.read_csv("not.csv")

In [27]:
print(df)

    Customer Name          age            Email   Country Purchase Amount  \
0   Isaac Morgan            17  ISAAC@email.com    ghana            2000
1        john doe  twenty five    john@email.com      USA            3000
2       MARY JANE          25     MARY@email.COM       Uk
3           Peter          200       peter@email    Kenya            5000
4             NaN           30      noemail@.com  Nigeria            4000
5            Anna           22   anna@email.com                      3500
6           Kwame          28    kwame@email.com    Ghana           $5300
7   Isaac Morgan            17   isaac@email.com    GHANA            2000

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [28]:
print(df.isnull().sum())

Customer Name      1
age                0
Email              0
Country            0
Purchase Amount    0
Date               0
dtype: int64

In [29]:
print(df)

    Customer Name          age            Email   Country Purchase Amount  \
0   Isaac Morgan            17  ISAAC@email.com    ghana            2000
1        john doe  twenty five    john@email.com      USA            3000
2       MARY JANE          25     MARY@email.COM       Uk
3           Peter          200       peter@email    Kenya            5000
4             NaN           30      noemail@.com  Nigeria            4000
5            Anna           22   anna@email.com                      3500
6           Kwame          28    kwame@email.com    Ghana           $5300
7   Isaac Morgan            17   isaac@email.com    GHANA            2000

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [30]:
df["Customer Name"] = df["Customer Name"].fillna("Unknown").mode()

In [31]:
print(df)

    Customer Name          age            Email   Country Purchase Amount  \
0   Isaac Morgan            17  ISAAC@email.com    ghana            2000
1            Anna  twenty five    john@email.com      USA            3000
2   Isaac Morgan           25     MARY@email.COM       Uk
3           Kwame          200       peter@email    Kenya            5000
4       MARY JANE           30      noemail@.com  Nigeria            4000
5           Peter           22   anna@email.com                      3500
6         Unknown          28    kwame@email.com    Ghana           $5300
7        john doe           17   isaac@email.com    GHANA            2000

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [32]:
print(df.isnull().sum())

Customer Name      0
age                0
Email              0
Country            0
Purchase Amount    0
Date               0
dtype: int64

In [33]:
print(df.duplicated().sum(),"Duplicates found")

0 Duplicates found

In [34]:
df.columns

Index(['Customer Name', 'age', 'Email ', 'Country', 'Purchase Amount', 'Date'], dtype='str')

In [35]:
df["Email "] = df["Email "].str.strip()

In [36]:
df.columns

Index(['Customer Name', 'age', 'Email ', 'Country', 'Purchase Amount', 'Date'], dtype='str')

In [37]:
print(df)

    Customer Name          age           Email   Country Purchase Amount  \
0   Isaac Morgan            17  ISAAC@email.com   ghana            2000
1            Anna  twenty five   john@email.com      USA            3000
2   Isaac Morgan           25    MARY@email.COM       Uk
3           Kwame          200      peter@email    Kenya            5000
4       MARY JANE           30     noemail@.com  Nigeria            4000
5           Peter           22   anna@email.com                     3500
6         Unknown          28   kwame@email.com    Ghana           $5300
7        john doe           17  isaac@email.com    GHANA            2000

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [38]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [39]:
df.dtypes

Customer Name      str
age                str
Email              str
Country            str
Purchase Amount    str
Date               str
dtype: object

In [40]:
print(df)

    Customer Name          age           Email   Country Purchase Amount  \
0   Isaac Morgan            17  ISAAC@email.com   ghana            2000
1            Anna  twenty five   john@email.com      USA            3000
2   Isaac Morgan           25    MARY@email.COM       Uk
3           Kwame          200      peter@email    Kenya            5000
4       MARY JANE           30     noemail@.com  Nigeria            4000
5           Peter           22   anna@email.com                     3500
6         Unknown          28   kwame@email.com    Ghana           $5300
7        john doe           17  isaac@email.com    GHANA            2000

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [41]:
df["age"] = pd.to_numeric(df["age"],errors="coerce")

In [42]:
df.dtypes

Customer Name          str
age                float64
Email                  str
Country                str
Purchase Amount        str
Date                   str
dtype: object

In [43]:
df["Purchase Amount"] = pd.to_numeric(df["Purchase Amount"],errors="coerce")

In [44]:
df.dtypes

Customer Name          str
age                float64
Email                  str
Country                str
Purchase Amount    float64
Date                   str
dtype: object

In [45]:
# df["Date"] = pd.to_datetime(["date"])
# print(df["Date"])

In [46]:
df.dtypes

Customer Name          str
age                float64
Email                  str
Country                str
Purchase Amount    float64
Date                   str
dtype: object

In [47]:
print(df)

    Customer Name    age           Email   Country  Purchase Amount  \
0   Isaac Morgan    17.0  ISAAC@email.com   ghana            2000.0
1            Anna    NaN   john@email.com      USA           3000.0
2   Isaac Morgan    25.0   MARY@email.COM       Uk              NaN
3           Kwame  200.0      peter@email    Kenya           5000.0
4       MARY JANE   30.0     noemail@.com  Nigeria           4000.0
5           Peter   22.0   anna@email.com                    3500.0
6         Unknown   28.0  kwame@email.com    Ghana              NaN
7        john doe   17.0  isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [48]:
print(df)

    Customer Name    age           Email   Country  Purchase Amount  \
0   Isaac Morgan    17.0  ISAAC@email.com   ghana            2000.0
1            Anna    NaN   john@email.com      USA           3000.0
2   Isaac Morgan    25.0   MARY@email.COM       Uk              NaN
3           Kwame  200.0      peter@email    Kenya           5000.0
4       MARY JANE   30.0     noemail@.com  Nigeria           4000.0
5           Peter   22.0   anna@email.com                    3500.0
6         Unknown   28.0  kwame@email.com    Ghana              NaN
7        john doe   17.0  isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [49]:
df["Country"] = df["Country"].astype(str)

In [50]:
print(df)

    Customer Name    age           Email   Country  Purchase Amount  \
0   Isaac Morgan    17.0  ISAAC@email.com   ghana            2000.0
1            Anna    NaN   john@email.com      USA           3000.0
2   Isaac Morgan    25.0   MARY@email.COM       Uk              NaN
3           Kwame  200.0      peter@email    Kenya           5000.0
4       MARY JANE   30.0     noemail@.com  Nigeria           4000.0
5           Peter   22.0   anna@email.com                    3500.0
6         Unknown   28.0  kwame@email.com    Ghana              NaN
7        john doe   17.0  isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [51]:
df["Country"] = df["Country"].str.title()

In [52]:
print(df)

    Customer Name    age           Email   Country  Purchase Amount  \
0   Isaac Morgan    17.0  ISAAC@email.com   Ghana            2000.0
1            Anna    NaN   john@email.com      Usa           3000.0
2   Isaac Morgan    25.0   MARY@email.COM       Uk              NaN
3           Kwame  200.0      peter@email    Kenya           5000.0
4       MARY JANE   30.0     noemail@.com  Nigeria           4000.0
5           Peter   22.0   anna@email.com                    3500.0
6         Unknown   28.0  kwame@email.com    Ghana              NaN
7        john doe   17.0  isaac@email.com    Ghana           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [53]:
df["age"] = df["age"].fillna(df["age"].median())

In [54]:
print(df)

    Customer Name    age           Email   Country  Purchase Amount  \
0   Isaac Morgan    17.0  ISAAC@email.com   Ghana            2000.0
1            Anna   25.0   john@email.com      Usa           3000.0
2   Isaac Morgan    25.0   MARY@email.COM       Uk              NaN
3           Kwame  200.0      peter@email    Kenya           5000.0
4       MARY JANE   30.0     noemail@.com  Nigeria           4000.0
5           Peter   22.0   anna@email.com                    3500.0
6         Unknown   28.0  kwame@email.com    Ghana              NaN
7        john doe   17.0  isaac@email.com    Ghana           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [55]:
df.loc[3,"age"] = 30
print(df)

    Customer Name   age           Email   Country  Purchase Amount  \
0   Isaac Morgan   17.0  ISAAC@email.com   Ghana            2000.0
1            Anna  25.0   john@email.com      Usa           3000.0
2   Isaac Morgan   25.0   MARY@email.COM       Uk              NaN
3           Kwame  30.0      peter@email    Kenya           5000.0
4       MARY JANE  30.0     noemail@.com  Nigeria           4000.0
5           Peter  22.0   anna@email.com                    3500.0
6         Unknown  28.0  kwame@email.com    Ghana              NaN
7        john doe  17.0  isaac@email.com    Ghana           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [56]:
df["age"] = df["age"].astype(int)

In [57]:
print(df)

    Customer Name  age           Email   Country  Purchase Amount  \
0   Isaac Morgan    17  ISAAC@email.com   Ghana            2000.0
1            Anna   25   john@email.com      Usa           3000.0
2   Isaac Morgan    25   MARY@email.COM       Uk              NaN
3           Kwame   30      peter@email    Kenya           5000.0
4       MARY JANE   30     noemail@.com  Nigeria           4000.0
5           Peter   22   anna@email.com                    3500.0
6         Unknown   28  kwame@email.com    Ghana              NaN
7        john doe   17  isaac@email.com    Ghana           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [58]:
print(df.isnull())

   Customer Name    age  Email   Country  Purchase Amount   Date
0          False  False   False    False            False  False
1          False  False   False    False            False  False
2          False  False   False    False             True  False
3          False  False   False    False            False  False
4          False  False   False    False            False  False
5          False  False   False    False            False  False
6          False  False   False    False             True  False
7          False  False   False    False            False  False

In [59]:
print(df.isnull().sum())

Customer Name      0
age                0
Email              0
Country            0
Purchase Amount    2
Date               0
dtype: int64

In [60]:
df["Purchase Amount"] = df["Purchase Amount"].fillna(df["Purchase Amount"].median())
print(df)

    Customer Name  age           Email   Country  Purchase Amount  \
0   Isaac Morgan    17  ISAAC@email.com   Ghana            2000.0
1            Anna   25   john@email.com      Usa           3000.0
2   Isaac Morgan    25   MARY@email.COM       Uk           3250.0
3           Kwame   30      peter@email    Kenya           5000.0
4       MARY JANE   30     noemail@.com  Nigeria           4000.0
5           Peter   22   anna@email.com                    3500.0
6         Unknown   28  kwame@email.com    Ghana           3250.0
7        john doe   17  isaac@email.com    Ghana           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [61]:
print(df.isnull().sum())

Customer Name      0
age                0
Email              0
Country            0
Purchase Amount    0
Date               0
dtype: int64

In [62]:
print(df["Date"].dtype)

str

In [63]:
df.dtypes

Customer Name          str
age                  int64
Email                  str
Country                str
Purchase Amount    float64
Date                   str
dtype: object

In [64]:
print(df)

    Customer Name  age           Email   Country  Purchase Amount  \
0   Isaac Morgan    17  ISAAC@email.com   Ghana            2000.0
1            Anna   25   john@email.com      Usa           3000.0
2   Isaac Morgan    25   MARY@email.COM       Uk           3250.0
3           Kwame   30      peter@email    Kenya           5000.0
4       MARY JANE   30     noemail@.com  Nigeria           4000.0
5           Peter   22   anna@email.com                    3500.0
6         Unknown   28  kwame@email.com    Ghana           3250.0
7        john doe   17  isaac@email.com    Ghana           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [65]:
df.loc[0,"Email "] = "isaac@email.com"
df.loc[2,"Email "] = "mary@email.com"
df.loc[3,"Email "] = "peter@email.com"
df.loc[4,"Email "] = "noemail@email.com"
print(df)
print(df.duplicated())
print(df.isnull())

    Customer Name  age             Email   Country  Purchase Amount  \
0   Isaac Morgan    17    isaac@email.com   Ghana            2000.0
1            Anna   25     john@email.com      Usa           3000.0
2   Isaac Morgan    25     mary@email.com       Uk           3250.0
3           Kwame   30    peter@email.com    Kenya           5000.0
4       MARY JANE   30  noemail@email.com  Nigeria           4000.0
5           Peter   22     anna@email.com                    3500.0
6         Unknown   28    kwame@email.com    Ghana           3250.0
7        john doe   17    isaac@email.com    Ghana           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool
   Customer Name    age  Email   Country  Purchase Amount   Date
0          False  False   False    False            False  False
1          False  False   False    False            False  False
2          False  False   False    False            False  False
3          False  False   False    False            False  False
4          False  False   False    False            False  False
5          False  False   False    False            False  False
6          False  False   False    False            False  False
7          False  False   False    False            False  False

In [66]:
df.columns

Index(['Customer Name', 'age', 'Email ', 'Country', 'Purchase Amount', 'Date'], dtype='str')

In [67]:
df["Email "] = df["Email "].str.replace(" ","")

In [68]:
df.columns

Index(['Customer Name', 'age', 'Email ', 'Country', 'Purchase Amount', 'Date'], dtype='str')

In [69]:
print(df)

    Customer Name  age             Email   Country  Purchase Amount  \
0   Isaac Morgan    17    isaac@email.com   Ghana            2000.0
1            Anna   25     john@email.com      Usa           3000.0
2   Isaac Morgan    25     mary@email.com       Uk           3250.0
3           Kwame   30    peter@email.com    Kenya           5000.0
4       MARY JANE   30  noemail@email.com  Nigeria           4000.0
5           Peter   22     anna@email.com                    3500.0
6         Unknown   28    kwame@email.com    Ghana           3250.0
7        john doe   17    isaac@email.com    Ghana           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [70]:
df["Country"] = df["Country"].str.upper() 
print(df)

    Customer Name  age             Email   Country  Purchase Amount  \
0   Isaac Morgan    17    isaac@email.com   GHANA            2000.0
1            Anna   25     john@email.com      USA           3000.0
2   Isaac Morgan    25     mary@email.com       UK           3250.0
3           Kwame   30    peter@email.com    KENYA           5000.0
4       MARY JANE   30  noemail@email.com  NIGERIA           4000.0
5           Peter   22     anna@email.com                    3500.0
6         Unknown   28    kwame@email.com    GHANA           3250.0
7        john doe   17    isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [71]:
df.loc[5,"Country"] = "AMERICA"

In [72]:
print(df)

    Customer Name  age             Email   Country  Purchase Amount  \
0   Isaac Morgan    17    isaac@email.com   GHANA            2000.0
1            Anna   25     john@email.com      USA           3000.0
2   Isaac Morgan    25     mary@email.com       UK           3250.0
3           Kwame   30    peter@email.com    KENYA           5000.0
4       MARY JANE   30  noemail@email.com  NIGERIA           4000.0
5           Peter   22     anna@email.com  AMERICA           3500.0
6         Unknown   28    kwame@email.com    GHANA           3250.0
7        john doe   17    isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [73]:
df["Country"].unique()

<StringArray>
['GHANA ', 'USA', 'UK', 'KENYA', 'NIGERIA', 'AMERICA', 'GHANA']
Length: 7, dtype: str

In [74]:
df["Country"].str.contains(" ")

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: Country, dtype: bool

In [75]:
df["Country"] = df["Country"].str.strip()

In [76]:
df["Country"].str.contains(" ")

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: Country, dtype: bool

In [77]:
df["Country"].unique()

<StringArray>
['GHANA', 'USA', 'UK', 'KENYA', 'NIGERIA', 'AMERICA']
Length: 6, dtype: str

In [78]:
df.columns

Index(['Customer Name', 'age', 'Email ', 'Country', 'Purchase Amount', 'Date'], dtype='str')

In [79]:
df["Email "].unique()

<StringArray>
[  'isaac@email.com',    'john@email.com',    'mary@email.com',
   'peter@email.com', 'noemail@email.com',    'anna@email.com',
   'kwame@email.com']
Length: 7, dtype: str

In [80]:
df["Customer Name"].unique()

<StringArray>
[' Isaac Morgan ',           'Anna',  'Isaac Morgan ',          'Kwame',
      'MARY JANE',          'Peter',        'Unknown',       'john doe']
Length: 8, dtype: str

In [81]:
df["age"].unique()

array([17, 25, 30, 22, 28])

In [82]:
df["Date"].unique()

<StringArray>
[  '2024/01/01',   '01-02-2024',   '2024-03-01', 'March 5 2024',
   '2024/04/01',   '2024-05-01',   '2024-06-01']
Length: 7, dtype: str

In [83]:
df.columns= df.columns.str.strip().str.replace(" ","_")
print(df)
df.columns

    Customer_Name  age              Email  Country  Purchase_Amount  \
0   Isaac Morgan    17    isaac@email.com    GHANA           2000.0
1            Anna   25     john@email.com      USA           3000.0
2   Isaac Morgan    25     mary@email.com       UK           3250.0
3           Kwame   30    peter@email.com    KENYA           5000.0
4       MARY JANE   30  noemail@email.com  NIGERIA           4000.0
5           Peter   22     anna@email.com  AMERICA           3500.0
6         Unknown   28    kwame@email.com    GHANA           3250.0
7        john doe   17    isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

Index(['Customer_Name', 'age', 'Email', 'Country', 'Purchase_Amount', 'Date'], dtype='str')

In [84]:
print(df)
df.columns

    Customer_Name  age              Email  Country  Purchase_Amount  \
0   Isaac Morgan    17    isaac@email.com    GHANA           2000.0
1            Anna   25     john@email.com      USA           3000.0
2   Isaac Morgan    25     mary@email.com       UK           3250.0
3           Kwame   30    peter@email.com    KENYA           5000.0
4       MARY JANE   30  noemail@email.com  NIGERIA           4000.0
5           Peter   22     anna@email.com  AMERICA           3500.0
6         Unknown   28    kwame@email.com    GHANA           3250.0
7        john doe   17    isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

Index(['Customer_Name', 'age', 'Email', 'Country', 'Purchase_Amount', 'Date'], dtype='str')

In [85]:
print(df.isnull().sum())

Customer_Name      0
age                0
Email              0
Country            0
Purchase_Amount    0
Date               0
dtype: int64

In [86]:
df[df["Date"].isna()]

Empty DataFrame
Columns: [Customer_Name, age, Email, Country, Purchase_Amount, Date]
Index: []

In [87]:
df["Date"] = df["Date"].fillna("2025-10-7")

In [88]:
print(df)

    Customer_Name  age              Email  Country  Purchase_Amount  \
0   Isaac Morgan    17    isaac@email.com    GHANA           2000.0
1            Anna   25     john@email.com      USA           3000.0
2   Isaac Morgan    25     mary@email.com       UK           3250.0
3           Kwame   30    peter@email.com    KENYA           5000.0
4       MARY JANE   30  noemail@email.com  NIGERIA           4000.0
5           Peter   22     anna@email.com  AMERICA           3500.0
6         Unknown   28    kwame@email.com    GHANA           3250.0
7        john doe   17    isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [89]:
df.dtypes

Customer_Name          str
age                  int64
Email                  str
Country                str
Purchase_Amount    float64
Date                   str
dtype: object

In [90]:
df["Date"].dtype

In [91]:
print(df.isnull().sum())

Customer_Name      0
age                0
Email              0
Country            0
Purchase_Amount    0
Date               0
dtype: int64

In [92]:
pd.melt(df)

           variable              value
0     Customer_Name      Isaac Morgan
1     Customer_Name               Anna
2     Customer_Name      Isaac Morgan
3     Customer_Name              Kwame
4     Customer_Name          MARY JANE
5     Customer_Name              Peter
6     Customer_Name            Unknown
7     Customer_Name           john doe
8               age                 17
9               age                 25
10              age                 25
11              age                 30
12              age                 30
13              age                 22
14              age                 28
15              age                 17
16            Email    isaac@email.com
17            Email     john@email.com
18            Email     mary@email.com
19            Email    peter@email.com
20            Email  noemail@email.com
21            Email     anna@email.com
22            Email    kwame@email.com
23            Email    isaac@email.com
24          Country              GHANA
25          Country                USA
26          Country                 UK
27          Country              KENYA
28          Country            NIGERIA
29          Country            AMERICA
30          Country              GHANA
31          Country              GHANA
32  Purchase_Amount             2000.0
33  Purchase_Amount             3000.0
34  Purchase_Amount             3250.0
35  Purchase_Amount             5000.0
36  Purchase_Amount             4000.0
37  Purchase_Amount             3500.0
38  Purchase_Amount             3250.0
39  Purchase_Amount             2000.0
40             Date         2024/01/01
41             Date         01-02-2024
42             Date         2024-03-01
43             Date       March 5 2024
44             Date         2024/04/01
45             Date         2024-05-01
46             Date         2024-06-01
47             Date         2024/01/01

In [93]:
print(df)

    Customer_Name  age              Email  Country  Purchase_Amount  \
0   Isaac Morgan    17    isaac@email.com    GHANA           2000.0
1            Anna   25     john@email.com      USA           3000.0
2   Isaac Morgan    25     mary@email.com       UK           3250.0
3           Kwame   30    peter@email.com    KENYA           5000.0
4       MARY JANE   30  noemail@email.com  NIGERIA           4000.0
5           Peter   22     anna@email.com  AMERICA           3500.0
6         Unknown   28    kwame@email.com    GHANA           3250.0
7        john doe   17    isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [94]:
df["Customer_Name"] = df["Customer_Name"].str.title()

In [95]:
print(df)

    Customer_Name  age              Email  Country  Purchase_Amount  \
0   Isaac Morgan    17    isaac@email.com    GHANA           2000.0
1            Anna   25     john@email.com      USA           3000.0
2   Isaac Morgan    25     mary@email.com       UK           3250.0
3           Kwame   30    peter@email.com    KENYA           5000.0
4       Mary Jane   30  noemail@email.com  NIGERIA           4000.0
5           Peter   22     anna@email.com  AMERICA           3500.0
6         Unknown   28    kwame@email.com    GHANA           3250.0
7        John Doe   17    isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [96]:
print(df.isnull().sum())
print(df.duplicated().sum(),"Duplicate found")
print(df.dtypes)

Customer_Name      0
age                0
Email              0
Country            0
Purchase_Amount    0
Date               0
dtype: int64
0 Duplicate found
Customer_Name          str
age                  int64
Email                  str
Country                str
Purchase_Amount    float64
Date                   str
dtype: object

In [97]:
df.columns

Index(['Customer_Name', 'age', 'Email', 'Country', 'Purchase_Amount', 'Date'], dtype='str')

In [98]:

print(df)

    Customer_Name  age              Email  Country  Purchase_Amount  \
0   Isaac Morgan    17    isaac@email.com    GHANA           2000.0
1            Anna   25     john@email.com      USA           3000.0
2   Isaac Morgan    25     mary@email.com       UK           3250.0
3           Kwame   30    peter@email.com    KENYA           5000.0
4       Mary Jane   30  noemail@email.com  NIGERIA           4000.0
5           Peter   22     anna@email.com  AMERICA           3500.0
6         Unknown   28    kwame@email.com    GHANA           3250.0
7        John Doe   17    isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [99]:
df["Customer_Name"].unique()

<StringArray>
[' Isaac Morgan ',           'Anna',  'Isaac Morgan ',          'Kwame',
      'Mary Jane',          'Peter',        'Unknown',       'John Doe']
Length: 8, dtype: str

In [100]:
df["Customer_Name"] = df["Customer_Name"].str.strip()

In [101]:
df["Customer_Name"].unique()

<StringArray>
['Isaac Morgan', 'Anna', 'Kwame', 'Mary Jane', 'Peter', 'Unknown', 'John Doe']
Length: 7, dtype: str

In [102]:
df["age"].unique()

array([17, 25, 30, 22, 28])

In [103]:
print(df)

  Customer_Name  age              Email  Country  Purchase_Amount  \
0  Isaac Morgan   17    isaac@email.com    GHANA           2000.0
1          Anna   25     john@email.com      USA           3000.0
2  Isaac Morgan   25     mary@email.com       UK           3250.0
3         Kwame   30    peter@email.com    KENYA           5000.0
4     Mary Jane   30  noemail@email.com  NIGERIA           4000.0
5         Peter   22     anna@email.com  AMERICA           3500.0
6       Unknown   28    kwame@email.com    GHANA           3250.0
7      John Doe   17    isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
2    2024-03-01
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [104]:
df = df.drop_duplicates(subset=["Customer_Name"])
print(df)

  Customer_Name  age              Email  Country  Purchase_Amount  \
0  Isaac Morgan   17    isaac@email.com    GHANA           2000.0
1          Anna   25     john@email.com      USA           3000.0
3         Kwame   30    peter@email.com    KENYA           5000.0
4     Mary Jane   30  noemail@email.com  NIGERIA           4000.0
5         Peter   22     anna@email.com  AMERICA           3500.0
6       Unknown   28    kwame@email.com    GHANA           3250.0
7      John Doe   17    isaac@email.com    GHANA           2000.0

           Date
0    2024/01/01
1    01-02-2024
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01
7    2024/01/01

In [105]:
df = df.drop_duplicates(subset=["Email"])
print(df)

  Customer_Name  age              Email  Country  Purchase_Amount  \
0  Isaac Morgan   17    isaac@email.com    GHANA           2000.0
1          Anna   25     john@email.com      USA           3000.0
3         Kwame   30    peter@email.com    KENYA           5000.0
4     Mary Jane   30  noemail@email.com  NIGERIA           4000.0
5         Peter   22     anna@email.com  AMERICA           3500.0
6       Unknown   28    kwame@email.com    GHANA           3250.0

           Date
0    2024/01/01
1    01-02-2024
3  March 5 2024
4    2024/04/01
5    2024-05-01
6    2024-06-01

In [106]:
df = df.reset_index(drop=True)
print(df)

  Customer_Name  age              Email  Country  Purchase_Amount  \
0  Isaac Morgan   17    isaac@email.com    GHANA           2000.0
1          Anna   25     john@email.com      USA           3000.0
2         Kwame   30    peter@email.com    KENYA           5000.0
3     Mary Jane   30  noemail@email.com  NIGERIA           4000.0
4         Peter   22     anna@email.com  AMERICA           3500.0
5       Unknown   28    kwame@email.com    GHANA           3250.0

           Date
0    2024/01/01
1    01-02-2024
2  March 5 2024
3    2024/04/01
4    2024-05-01
5    2024-06-01

In [107]:
df.loc[5,"Customer_Name"] = "Kwame"
df.loc[2,"Customer_Name"] = "Peter"
df.loc[4,"Customer_Name"] = "Anna"
df.loc[1,"Customer_Name"] = "John"
df.loc[3,"Email"] = "maryjane@email.com"
print(df)

  Customer_Name  age               Email  Country  Purchase_Amount  \
0  Isaac Morgan   17     isaac@email.com    GHANA           2000.0
1          John   25      john@email.com      USA           3000.0
2         Peter   30     peter@email.com    KENYA           5000.0
3     Mary Jane   30  maryjane@email.com  NIGERIA           4000.0
4          Anna   22      anna@email.com  AMERICA           3500.0
5         Kwame   28     kwame@email.com    GHANA           3250.0

           Date
0    2024/01/01
1    01-02-2024
2  March 5 2024
3    2024/04/01
4    2024-05-01
5    2024-06-01

In [108]:
df.loc[4,"Country"] = "UK"

In [109]:
print(df)

  Customer_Name  age               Email  Country  Purchase_Amount  \
0  Isaac Morgan   17     isaac@email.com    GHANA           2000.0
1          John   25      john@email.com      USA           3000.0
2         Peter   30     peter@email.com    KENYA           5000.0
3     Mary Jane   30  maryjane@email.com  NIGERIA           4000.0
4          Anna   22      anna@email.com       UK           3500.0
5         Kwame   28     kwame@email.com    GHANA           3250.0

           Date
0    2024/01/01
1    01-02-2024
2  March 5 2024
3    2024/04/01
4    2024-05-01
5    2024-06-01

In [110]:
df["age"].mean()
df["Purchase_Amount"].max()
df["Country"].value_counts()

Country
GHANA      2
USA        1
KENYA      1
NIGERIA    1
UK         1
Name: count, dtype: int64

In [111]:
df["Email"].value_counts()

Email
isaac@email.com       1
john@email.com        1
peter@email.com       1
maryjane@email.com    1
anna@email.com        1
kwame@email.com       1
Name: count, dtype: int64

In [112]:
print(df)

  Customer_Name  age               Email  Country  Purchase_Amount  \
0  Isaac Morgan   17     isaac@email.com    GHANA           2000.0
1          John   25      john@email.com      USA           3000.0
2         Peter   30     peter@email.com    KENYA           5000.0
3     Mary Jane   30  maryjane@email.com  NIGERIA           4000.0
4          Anna   22      anna@email.com       UK           3500.0
5         Kwame   28     kwame@email.com    GHANA           3250.0

           Date
0    2024/01/01
1    01-02-2024
2  March 5 2024
3    2024/04/01
4    2024-05-01
5    2024-06-01

In [113]:
df.head()

,Customer_Name,age,Email,Country,Purchase_Amount,Date
0,Isaac Morgan,17,isaac@email.com,GHANA,2000.0,2024/01/01
1,John,25,john@email.com,USA,3000.0,01-02-2024
2,Peter,30,peter@email.com,KENYA,5000.0,March 5 2024
3,Mary Jane,30,maryjane@email.com,NIGERIA,4000.0,2024/04/01
4,Anna,22,anna@email.com,UK,3500.0,2024-05-01

In [120]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [121]:
print(df["Date"].dtype)

datetime64[us]

In [122]:
df.head()

  Customer_Name  age               Email  Country  Purchase_Amount       Date
0  Isaac Morgan   17     isaac@email.com    GHANA           2000.0 2024-01-01
1          John   25      john@email.com      USA           3000.0        NaT
2         Peter   30     peter@email.com    KENYA           5000.0        NaT
3     Mary Jane   30  maryjane@email.com  NIGERIA           4000.0 2024-04-01
4          Anna   22      anna@email.com       UK           3500.0        NaT

In [126]:
df.loc[1, "Date"] = "2024-02-01"
df.loc[2, "Date"] = "2024-04-05"
df.loc[4, "Date"] = "2025-06-07"

In [128]:
print(df["Date"].dtype)

datetime64[us]

In [129]:
df.head()

  Customer_Name  age               Email  Country  Purchase_Amount       Date
0  Isaac Morgan   17     isaac@email.com    GHANA           2000.0 2024-01-01
1          John   25      john@email.com      USA           3000.0 2024-02-01
2         Peter   30     peter@email.com    KENYA           5000.0 2024-04-05
3     Mary Jane   30  maryjane@email.com  NIGERIA           4000.0 2024-04-01
4          Anna   22      anna@email.com       UK           3500.0 2025-06-07

In [131]:
df.dtypes

Customer_Name                 str
age                         int64
Email                         str
Country                       str
Purchase_Amount           float64
Date               datetime64[us]
dtype: object

In [132]:
df.head()

  Customer_Name  age               Email  Country  Purchase_Amount       Date
0  Isaac Morgan   17     isaac@email.com    GHANA           2000.0 2024-01-01
1          John   25      john@email.com      USA           3000.0 2024-02-01
2         Peter   30     peter@email.com    KENYA           5000.0 2024-04-05
3     Mary Jane   30  maryjane@email.com  NIGERIA           4000.0 2024-04-01
4          Anna   22      anna@email.com       UK           3500.0 2025-06-07