In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.isnull().sum()

Year                           0
Industry_aggregation_NZSIOC    0
Industry_code_NZSIOC           0
Industry_name_NZSIOC           0
Units                          0
Variable_code                  0
Variable_name                  0
Variable_category              0
Value                          0
Industry_code_ANZSIC06         0
dtype: int64

In [4]:
print(df.duplicated().sum(),"Duplicates")

0 Duplicates

In [5]:
df = df.drop_duplicates()
print(df)

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]

In [6]:
print(df)
df.isnull()
df.isnull().sum()

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]

Year                           0
Industry_aggregation_NZSIOC    0
Industry_code_NZSIOC           0
Industry_name_NZSIOC           0
Units                          0
Variable_code                  0
Variable_name                  0
Variable_category              0
Value                          0
Industry_code_ANZSIC06         0
dtype: int64

In [7]:
df = df.dropna()
print(df)

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]

In [8]:
df = df.dropna(axis=1)
print(df)

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]

In [9]:
pd.melt(df)

,variable,value
0,Year,2024
1,Year,2024
2,Year,2024
3,Year,2024
4,Year,2024
...,...,...
556195,Industry_code_ANZSIC06,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
556196,Industry_code_ANZSIC06,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
556197,Industry_code_ANZSIC06,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
556198,Industry_code_ANZSIC06,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
556199,Industry_code_ANZSIC06,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [10]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55620 entries, 0 to 55619
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         55620 non-null  int64
 1   Industry_aggregation_NZSIOC  55620 non-null  str
 2   Industry_code_NZSIOC         55620 non-null  str
 3   Industry_name_NZSIOC         55620 non-null  str
 4   Units                        55620 non-null  str
 5   Variable_code                55620 non-null  str
 6   Variable_name                55620 non-null  str
 7   Variable_category            55620 non-null  str
 8   Value                        55620 non-null  str
 9   Industry_code_ANZSIC06       55620 non-null  str
dtypes: int64(1), str(9)
memory usage: 4.2 MB

In [12]:
df.describe()

               Year
count  55620.000000
mean    2018.500000
std        3.452084
min     2013.000000
25%     2015.750000
50%     2018.500000
75%     2021.250000
max     2024.000000

In [13]:
print(df.columns)

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='str')

In [14]:
df["Year"].unique()

array([2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014,
       2013])

In [15]:
df["Year"].value_counts()

Year
2024    4635
2023    4635
2022    4635
2021    4635
2020    4635
2019    4635
2018    4635
2017    4635
2016    4635
2015    4635
2014    4635
2013    4635
Name: count, dtype: int64

In [16]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
55615    False
55616    False
55617    False
55618    False
55619    False
Length: 55620, dtype: bool

In [17]:
print(df)

# df["alpha"].mean()
# df["epsilon"].max()
# df["gamma"].value_counts()

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]

In [18]:
df = pd.read_csv("m-data.csv")

In [19]:
print(df)

     alpha  beta  gamma  delta  epsilon zeta eta
0        2    48     12    240      3.0  Yes  AZ
1        3    46     18    230      5.0  NaN  VT
2        4    44     24    220      7.0   No  PA
3        5    42     30    210      9.0  Yes  OK
4        6    44     36    220     11.0  Yes  MD
..     ...   ...    ...    ...      ...  ...  ..
160     84     4    504     20    323.0  Yes  LA
161     84     6    504     30    325.0  Yes  MI
162     84     8    504     40      NaN   No  NJ
163     84    -9    504    -45    329.0  Yes  LA
164     85    -9    510    -45    331.0  Yes  NJ

[165 rows x 7 columns]

In [20]:
print(df.isnull().sum())

alpha       0
beta        0
gamma       0
delta       0
epsilon    24
zeta       19
eta         0
dtype: int64

In [21]:
print(df.duplicated().sum(), "Duplicate found")

0 Duplicate found

In [22]:
df["epsilon"] = df["epsilon"].fillna(df["epsilon"].median())

In [23]:
print(df)

     alpha  beta  gamma  delta  epsilon zeta eta
0        2    48     12    240      3.0  Yes  AZ
1        3    46     18    230      5.0  NaN  VT
2        4    44     24    220      7.0   No  PA
3        5    42     30    210      9.0  Yes  OK
4        6    44     36    220     11.0  Yes  MD
..     ...   ...    ...    ...      ...  ...  ..
160     84     4    504     20    323.0  Yes  LA
161     84     6    504     30    325.0  Yes  MI
162     84     8    504     40    163.0   No  NJ
163     84    -9    504    -45    329.0  Yes  LA
164     85    -9    510    -45    331.0  Yes  NJ

[165 rows x 7 columns]

In [24]:
print(df.isnull().sum())

alpha       0
beta        0
gamma       0
delta       0
epsilon     0
zeta       19
eta         0
dtype: int64

In [25]:
print(df)

     alpha  beta  gamma  delta  epsilon zeta eta
0        2    48     12    240      3.0  Yes  AZ
1        3    46     18    230      5.0  NaN  VT
2        4    44     24    220      7.0   No  PA
3        5    42     30    210      9.0  Yes  OK
4        6    44     36    220     11.0  Yes  MD
..     ...   ...    ...    ...      ...  ...  ..
160     84     4    504     20    323.0  Yes  LA
161     84     6    504     30    325.0  Yes  MI
162     84     8    504     40    163.0   No  NJ
163     84    -9    504    -45    329.0  Yes  LA
164     85    -9    510    -45    331.0  Yes  NJ

[165 rows x 7 columns]

In [26]:
print(pd.melt(df))

     variable value
0       alpha     2
1       alpha     3
2       alpha     4
3       alpha     5
4       alpha     6
...       ...   ...
1150      eta    LA
1151      eta    MI
1152      eta    NJ
1153      eta    LA
1154      eta    NJ

[1155 rows x 2 columns]

In [27]:
print(df)

     alpha  beta  gamma  delta  epsilon zeta eta
0        2    48     12    240      3.0  Yes  AZ
1        3    46     18    230      5.0  NaN  VT
2        4    44     24    220      7.0   No  PA
3        5    42     30    210      9.0  Yes  OK
4        6    44     36    220     11.0  Yes  MD
..     ...   ...    ...    ...      ...  ...  ..
160     84     4    504     20    323.0  Yes  LA
161     84     6    504     30    325.0  Yes  MI
162     84     8    504     40    163.0   No  NJ
163     84    -9    504    -45    329.0  Yes  LA
164     85    -9    510    -45    331.0  Yes  NJ

[165 rows x 7 columns]

In [28]:
df["zeta"] = df["zeta"].fillna("Yes")

In [29]:
print(df.isnull().sum())

alpha      0
beta       0
gamma      0
delta      0
epsilon    0
zeta       0
eta        0
dtype: int64

In [30]:
print(df)

     alpha  beta  gamma  delta  epsilon zeta eta
0        2    48     12    240      3.0  Yes  AZ
1        3    46     18    230      5.0  Yes  VT
2        4    44     24    220      7.0   No  PA
3        5    42     30    210      9.0  Yes  OK
4        6    44     36    220     11.0  Yes  MD
..     ...   ...    ...    ...      ...  ...  ..
160     84     4    504     20    323.0  Yes  LA
161     84     6    504     30    325.0  Yes  MI
162     84     8    504     40    163.0   No  NJ
163     84    -9    504    -45    329.0  Yes  LA
164     85    -9    510    -45    331.0  Yes  NJ

[165 rows x 7 columns]

In [31]:
print(df.isnull().sum())

alpha      0
beta       0
gamma      0
delta      0
epsilon    0
zeta       0
eta        0
dtype: int64

In [32]:
df.loc[1,"zeta"] = "No"

In [33]:
print(df)

     alpha  beta  gamma  delta  epsilon zeta eta
0        2    48     12    240      3.0  Yes  AZ
1        3    46     18    230      5.0   No  VT
2        4    44     24    220      7.0   No  PA
3        5    42     30    210      9.0  Yes  OK
4        6    44     36    220     11.0  Yes  MD
..     ...   ...    ...    ...      ...  ...  ..
160     84     4    504     20    323.0  Yes  LA
161     84     6    504     30    325.0  Yes  MI
162     84     8    504     40    163.0   No  NJ
163     84    -9    504    -45    329.0  Yes  LA
164     85    -9    510    -45    331.0  Yes  NJ

[165 rows x 7 columns]

In [34]:
df.loc[164,"zeta"] = "No"
print(df)

     alpha  beta  gamma  delta  epsilon zeta eta
0        2    48     12    240      3.0  Yes  AZ
1        3    46     18    230      5.0   No  VT
2        4    44     24    220      7.0   No  PA
3        5    42     30    210      9.0  Yes  OK
4        6    44     36    220     11.0  Yes  MD
..     ...   ...    ...    ...      ...  ...  ..
160     84     4    504     20    323.0  Yes  LA
161     84     6    504     30    325.0  Yes  MI
162     84     8    504     40    163.0   No  NJ
163     84    -9    504    -45    329.0  Yes  LA
164     85    -9    510    -45    331.0   No  NJ

[165 rows x 7 columns]

In [35]:
print(df.duplicated().sum(), "Duplicates found")

0 Duplicates found

In [36]:
print(df.isnull().sum())

alpha      0
beta       0
gamma      0
delta      0
epsilon    0
zeta       0
eta        0
dtype: int64

In [37]:
df = df.dropna()

In [38]:
print(df)

     alpha  beta  gamma  delta  epsilon zeta eta
0        2    48     12    240      3.0  Yes  AZ
1        3    46     18    230      5.0   No  VT
2        4    44     24    220      7.0   No  PA
3        5    42     30    210      9.0  Yes  OK
4        6    44     36    220     11.0  Yes  MD
..     ...   ...    ...    ...      ...  ...  ..
160     84     4    504     20    323.0  Yes  LA
161     84     6    504     30    325.0  Yes  MI
162     84     8    504     40    163.0   No  NJ
163     84    -9    504    -45    329.0  Yes  LA
164     85    -9    510    -45    331.0   No  NJ

[165 rows x 7 columns]

In [39]:
pd.melt(df)

     variable value
0       alpha     2
1       alpha     3
2       alpha     4
3       alpha     5
4       alpha     6
...       ...   ...
1150      eta    LA
1151      eta    MI
1152      eta    NJ
1153      eta    LA
1154      eta    NJ

[1155 rows x 2 columns]

In [40]:
df.head()

   alpha  beta  gamma  delta  epsilon zeta eta
0      2    48     12    240      3.0  Yes  AZ
1      3    46     18    230      5.0   No  VT
2      4    44     24    220      7.0   No  PA
3      5    42     30    210      9.0  Yes  OK
4      6    44     36    220     11.0  Yes  MD

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   alpha    165 non-null    int64
 1   beta     165 non-null    int64
 2   gamma    165 non-null    int64
 3   delta    165 non-null    int64
 4   epsilon  165 non-null    float64
 5   zeta     165 non-null    str
 6   eta      165 non-null    str
dtypes: float64(1), int64(4), str(2)
memory usage: 9.2 KB

In [42]:
df.describe()

            alpha        beta       gamma       delta     epsilon
count  165.000000  165.000000  165.000000  165.000000  165.000000
mean    46.169697   17.921212  277.018182   89.606061  164.533333
std     24.371521   17.769180  146.229125   88.845900   89.098228
min      2.000000  -11.000000   12.000000  -55.000000    3.000000
25%     28.000000    7.000000  168.000000   35.000000   95.000000
50%     44.000000   15.000000  264.000000   75.000000  163.000000
75%     65.000000   32.000000  390.000000  160.000000  233.000000
max     85.000000   50.000000  510.000000  250.000000  331.000000

In [43]:
print(df.columns)

Index(['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta'], dtype='str')

In [44]:
df["beta"].unique()

array([ 48,  46,  44,  42,  50,  40,  38,  36,  34,  32,  49,  47,  43,
        37,  31,  41,  35,  33,  27,  24,  21,  18,  15,  12,   9,  10,
        11,  13,  16,  19,  22,  26,  25,  23,  17,   7,   5,   3,   1,
        -1,  -3,  -5,  -7,  -9, -11, -10,  -8,  -4,  -2,   0,   2,   4,
         6,   8])

In [45]:
print(df)

     alpha  beta  gamma  delta  epsilon zeta eta
0        2    48     12    240      3.0  Yes  AZ
1        3    46     18    230      5.0   No  VT
2        4    44     24    220      7.0   No  PA
3        5    42     30    210      9.0  Yes  OK
4        6    44     36    220     11.0  Yes  MD
..     ...   ...    ...    ...      ...  ...  ..
160     84     4    504     20    323.0  Yes  LA
161     84     6    504     30    325.0  Yes  MI
162     84     8    504     40    163.0   No  NJ
163     84    -9    504    -45    329.0  Yes  LA
164     85    -9    510    -45    331.0   No  NJ

[165 rows x 7 columns]

In [46]:
print(df.head(4))

   alpha  beta  gamma  delta  epsilon zeta eta
0      2    48     12    240      3.0  Yes  AZ
1      3    46     18    230      5.0   No  VT
2      4    44     24    220      7.0   No  PA
3      5    42     30    210      9.0  Yes  OK

In [47]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
160    False
161    False
162    False
163    False
164    False
Length: 165, dtype: bool

In [48]:
df.head()

   alpha  beta  gamma  delta  epsilon zeta eta
0      2    48     12    240      3.0  Yes  AZ
1      3    46     18    230      5.0   No  VT
2      4    44     24    220      7.0   No  PA
3      5    42     30    210      9.0  Yes  OK
4      6    44     36    220     11.0  Yes  MD